#bot.token=8330765498:AAFYjrRYlZoXMLy4f6vvSH4S9CaxnviO71g
bot.token=${BOT_TOKEN}
client.api.url=https://client.rozklad.org/files/rozklad/rr/r_1471.html

admin.chat.id=372739090

#db.name=jdbc:postgresql://34.88.10.183:5432/botdb

#db.name=jdbc:postgresql://localhost:5432/school_bot_db
#db.username=postgres
#db.password=k0koSS1KKK
db.name=${DB_NAME}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}